DROP DATABASE IF EXISTS employee_db;
CREATE DATABASE employee_db;

USE employee_db;

CREATE TABLE departments (
id INT NOT NULL AUTO_INCREMENT,
);


CREATE TABLE roles (
id INT NOT NULL AUTO_INCREMENT,
);

CREATE TABLE employees (
id INT NOT NULL AUTO_INCREMENT,
);